codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 90%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 2%
        base: auto

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "tests/"
  - "coverage/"
  - "node_modules/"
  - "*.test.js"
  - "jest.config.*"