name: Manual Publish

on:
  workflow_dispatch:
    inputs:
      npm_tag:
        description: 'NPM tag to publish under (latest, beta, alpha, etc.)'
        required: true
        default: 'latest'
        type: choice
        options:
        - latest
        - beta
        - alpha
        - next
      dry_run:
        description: 'Run in dry-run mode (test publish without actually publishing)'
        required: false
        default: false
        type: boolean

jobs:
  manual-publish:
    name: Manual NPM Publish
    runs-on: ubuntu-latest
    # Allow manual publish from master or dev branch
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run unit tests
      run: npm test
      
    - name: Build package (if applicable)
      run: npm run build --if-present
      
    - name: Dry run publish
      if: ${{ inputs.dry_run }}
      run: npm publish --dry-run --tag ${{ inputs.npm_tag }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Publish to NPM
      if: ${{ !inputs.dry_run }}
      run: npm publish --tag ${{ inputs.npm_tag }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Create GitHub Release (if latest tag)
      if: ${{ !inputs.dry_run && inputs.npm_tag == 'latest' }}
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.npm_package_version }}
        release_name: Release v${{ env.npm_package_version }}
        body: |
          ## Changes
          
          See [CHANGELOG.md](https://github.com/cwysong85/msrp-node-lib/blob/main/CHANGELOG.md) for details.
          
          ## Installation
          
          ```bash
          npm install msrp-node-lib@${{ env.npm_package_version }}
          ```
        draft: false
        prerelease: false